# Site
repository: brmochel92/brmochel92
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Brandon Mochel
title: Software Engineer
email: brandonmochel@ieee.org
website: https://brmochel92.github.io/brmochel92/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  brmochel92
linkedin_username: brandonmochel

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brandon and I am currently attending the Georgia Institute of Technologies MS CS program (OMSCS) with a specialization
  in Machine Learning.  
  
  My most recent role was a Systems Services Representative at IBM where I was involved with a lot of hardware repairs on various servers
  and workstations.  Prior to this, I was a recruiter and the sole developer at AMB Construction (designed web page, integrated and created
  database) for a little over two years.  

  My goal is to find a software company where I am able to collaborate as well as work on larger-scale projects, since this is something
  I currently lack.  I have no problem working an associate-level position to prove myself before working into a more graduated role.

  I am most skilled in: <mark>Python</mark> and <mark>C#</mark>.  I also know Java, Javascript (React, Angular, jQuery), HTML, CSS, and SQL.  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Consumer Mart
        link: github.com/brmochel92/Consumer_Mart
        # link_text: Project Website
        additional_links:
          - title:  brmochel92/Consumer_Mart
            icon: fab fa-github
            url: github.com/brmochel92/Consumer_Mart
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Consumer Mart is a full-stack E-Commerce Web Application that was created with RESTful API services, a relational database, and an angular front-end which was 
          developed with the Repository/MVC architecture on .NET Core Framework.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IBM
        link: https://www.ibm.com/us-en/
        # link_text: ibm.com
        sub_title: Back-End Developer
        caption: August 2019 - Present
        description: | # this will include new lines to allow paragraphs
          Created RESTful API services and documentation per client requirements and specifications.  Involved a lot of collaboration from day-to-day with other developers in a remote
          environment.  Wrote complex SQL queries and worked with stored procedures on Oracle and other SQL relational databases such as IBM Db2.  Experience deploying microservices and 
          applications on IBM Cloud and working with containers such as docker or k8s.  

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Georgia Institute of Technology
        caption: 2021-2023 (Projected)
        sub_title: MS Computer Science
        description: | # this will include new lines to allow paragraphs
          Specialization in Interactive Intelligence. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some other things I enjoy doing outside of Software Development:
      - Traveling
      - Reading
      - Home Lab

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
