# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Brandon Mochel
title: Software Engineer
email: brandonmochel@ieee.org
website: https://brmochel92.github.io/brmochel92/

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  brmochel92
linkedin_username: brandonmochel

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brandon and I am currently attending Georgia Institue of Technology as a graduate student in pursuit of my Masters in Computer Science with a specialization in 
  Computing Systems.  I have 4 years of professional experience as a full-stack Software Developer, two of which was spent at IBM as a back-end developer. 

  I am most skilled in: <mark>C#/.NET</mark> and <mark>.NET</mark>.  I also know Python, Java, Javascript (React, Angular, jQuery), HTML, and CSS.  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Consumer Mart
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  brmochel92/Consumer_Mart
            icon: fab fa-github
            url: github.com/brmochel92/Consumer_Mart
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Consumer Mart is a full-stack E-Commerce Web Application that was created with RESTful API services, a relational database, and an angular front-end which was 
          developed with the Repository/MVC architecture on .NET Core Framework.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IBM
        link: https://www.ibm.com/us-en/
        # link_text: ibm.com
        sub_title: Back-End Developer
        caption: August 2019 - Present
        description: | # this will include new lines to allow paragraphs
          Created RESTful API services and documentation per client requirements and specifications.  Involved a lot of collaboration from day-to-day with other developers in a remote
          environment.  Wrote complex SQL queries and worked with stored procedures on Oracle and other SQL relational databases such as IBM Db2.  Experience deploying microservices and 
          applications on IBM Cloud and working with containers such as docker or k8s.  

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Georgia Institute of Technology
        caption: 2016 - 2021
        sub_title: MS Computer Science
        description: | # this will include new lines to allow paragraphs
          

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Traveling
      - Reading
      - Home Lab

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
